### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by wangluyi1982** [earhian/Humpback-Whale-Identification-1st-#8]
Ran into two problems. 

1.
 
bboxs.csv file not found.  I am assuming that the bbox_by_masks.csv is the correct bboxs.csv file

2.

Cuda Out of Memory Error. 
Having 2 1080Ti GPU with 11G memory each. Got the  OOM error as following. 

```
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    train(freeze, fold_index, model_name, min_num_class, checkPoint_start, lr, batch_size)
  File "train.py", line 261, in train
    global_feat, local_feat, results = data_parallel(model,images)
```

changing batch_size from 12 to 6 doesn't help to solve this.  Would you like to share your training environment. Thanks.

**Comment by earhian** [comment]
5 titan x(pascal) ：）

**Comment by wangluyi1982** [comment]
Thanks for the reply.  i update device_ids to specify the gpus on my machine and update the batch size to 4 accordingly. It works now. 

Thanks.
